name: les-foulees-prod

services:
  app:
    build:
      context: .
      target: runner # Cible l'étape finale optimisée
      args:
        JWT_SECRET: ${JWT_SECRET}
        DATABASE_URL: ${DATABASE_URL}
        RESEND_API_KEY: ${RESEND_API_KEY}
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "3000:3000"
    restart: always # Redémarre automatiquement en cas de crash
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lesfoulees
    volumes:
      - db-data-prod:/var/lib/postgresql/data

volumes:
  db-data-prod: