FROM node:22-alpine

WORKDIR /app

# On installe les dépendances en premier (optimisation du cache Docker)
COPY package*.json ./
RUN npm install

# On génère Prisma ici aussi
COPY prisma ./prisma/
RUN npx prisma generate

# On copie le reste du code
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]